### ISSUE TITLE
Building with make

### ISSUE THREAD

**Issue by vegardjervell** [smrfeld/cmake_cpp_pybind11_tutorial#4] opened 2021-09-02 12:50 UTC
I am learning this for the first time, hence my use of this tutorial, so this is likely a result of my inexperience. But maybe someone else has the same issue..

I am running cmake 3.19.7 and GNU Make 3.81 on macOS 10.14.6.

When I've run `cmake ..` from the cpp/build directory i get the output
>  -- Configuring done
>  -- Generating done
>  -- Build files have been written to: /Users/(...)/pybind_tutorial/cpp/build

Then, when i run `make`, i get `make: *** No targets specified and no makefile found.  Stop.`
Running `make install` returns `make: *** No rule to make target 'install'.  Stop.`.

My project structure is as described in the tutorial:

>  cpp/build
>  cpp/CMakeLists.txt
>  cpp/include/automobile
>  cpp/include/automobile_bits/motorcycle.hpp
>  cpp/src/motorcycle.cpp

After running the `cmake ..` command, the cpp/build directory holds the files

> build.ninja
> cmake_install.cmake
> CMakeCache.txt
> compile_commands.json
> CPackConfig.cmake
> CPackSourceConfig.cmake
> CTestTestfile.cmake
> DartConfiguration.tcl

The cpp/build/CMakeFiles directory contains

> cmake.check_cache
> CMakeOutput.log
> rules.ninja
> TargetDirectories.txt
> automobile.dir/src (empty directory)
> 3.19.7 (what looks like standard version-specific cmake files)

As said, I feel like this is a product of my inexperience, but any help getting this to work would be greatly appreciated. 

Edit:
Following [this](https://www.youtube.com/watch?v=_5T70cAXDJ0) tutorial worked, although i can't seem to understand why that worked and not your tutorial, I'm guessing it has something to do with the different `CMakeLists.txt` files? I prefer written tutorials to videos, but that video is the only thing I've come across in over a day that ended up working for me.

**Comment by smrfeld** [comment] 2021-09-17 18:53
I cannot reproduce this - when I clone the repo, `cd` into the `cpp` directory, then:
```
mkdir build
cd build
cmake ..
```

The build directory then contains:
```
cmake_install.cmake
CMakeCache.txt
CMakeFiles/
Makefile
```
So I've got a makefile. Then I can just run:
```
make
```
and in the `build` folder I will get a new file: `libautomobile.dylib` as desired.

I've got cmake `3.18.3`, make `3.81` (same as you), Mac `11.4`. Unless `cmake` has undergone some changes `3.18.3 -> 3.19.7` I can't explain it - maybe try cloning the repo fresh again as described here and see if it works

**Comment by smrfeld** [comment] 2021-09-23 18:55
Ping if this is still an active issue, else I will close it

**Comment by vegardjervell** [comment] 2021-09-23 19:53
Hi, sorry for late answer. I eventually got it working a couple days ago after reinstalling cmake and cleansing my pc of various compilers i dont need anymore and such. I don't really have a good explanation for why it didn't work the first time...

**Comment by smrfeld** [comment] 2021-09-25 05:29
Great to hear! :)

**Closed as completed by smrfeld** 2021-09-25 05:29 UTC
